version: '3.8'

services:
  ai-iam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-iam-service
    ports:
      - "8080:8080"
    environment:
      - IAM_JWT_SECRET=my-secure-jwt-secret
      - ML_SERVICE_URL=http://ml-service:8001
    volumes:
      - ./data:/app/data
    depends_on:
      - ml-service
    restart: unless-stopped

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: ai-iam-ml-service
    ports:
      - "8001:8001"
    volumes:
      - ./ml-service/models:/app/models
    restart: unless-stopped

volumes:
  ml_models: